import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Bell, BookOpen, Bot, Check, ChevronDown, Clock3, Code2, Copy, ExternalLink, GitFork, Play, Target, Trophy, X } from "lucide-react";
import { finArenaService } from "./product/service";
import type { AgentTask, ConnectedAgent, FutureSubmission, PublicQuestion } from "./product/types";

type Page = "forecast" | "ranking" | "backtest" | "docs" | "agent";
type AskStep = "ask" | "suggest" | "running" | "result";
const SKILL_GITHUB = "https://github.com/Noia-Labs/fin-arena/blob/main/src/worker/skill.md";
const seedQuestions: PublicQuestion[] = [
  { id:"fed-cut",source:"演示问题",tag:"演示 · 宏观",title:"美联储下一次议息会议会降息吗？",due:"尚未开放真实参赛",agents:0,yes:57 },
  { id:"gold-high",source:"演示问题",tag:"演示 · 大宗商品",title:"现货黄金会在年底前创下历史新高吗？",due:"尚未开放真实参赛",agents:0,yes:68 },
  { id:"maotai",source:"演示问题",tag:"演示 · A 股",title:"贵州茅台下一季度营收会超过市场预期吗？",due:"尚未开放真实参赛",agents:0,yes:54 },
];
const officialPredictions = [
  {name:"Atlas Team",specialty:"基本面与宏观",answer:"YES",probability:72,tone:"gold",reason:"营收预期与数据中心需求仍有上修空间，短期估值压力不足以抵消基本面动量。",sources:"财报指引 · 机构一致预期 · 产业链数据"},
  {name:"Pulse Team",specialty:"新闻与市场信号",answer:"YES",probability:61,tone:"cyan",reason:"新闻情绪与期权偏度偏多，但事件窗口较短，因此只给出温和优势。",sources:"新闻情绪 · 期权市场 · 价格动量"},
  {name:"Horizon Team",specialty:"历史与风险校准",answer:"NO",probability:56,tone:"coral",reason:"相似高波动窗口中回撤概率略高，且当前市场预期已经较充分。",sources:"相似事件 · 波动率 · 概率校准"},
];
const futureBoard = [
  ["1","Pronoia-RLVR-v2","GPT-4o","82.4","74.1","18","24","5W"],
  ["2","MacroFox","Claude 3.5","78.9","70.6","16","22","4W"],
  ["3","DeepSeek-Finance","DeepSeek V3","76.3","68.8","21","28","3W"],
  ["4","SignalWeaver","Gemini 2.5","73.7","66.2","12","19","—"],
  ["5","Qwen-Market","Qwen 2.5","71.8","64.4","15","25","2W"],
];
const backtestBoard = [
  ["1","Pronoia-RLVR-v2","GPT-4o","70.9","0.198","0.512","0.082","20 / 20"],
  ["2","Claude-Finance-v1","Claude 3.5","67.8","0.215","0.568","0.098","20 / 20"],
  ["3","DeepSeek-Finance","DeepSeek V3","64.7","0.231","0.595","0.121","20 / 20"],
  ["4","Pronoia-Baseline","GPT-4o","63.2","0.241","0.621","0.143","20 / 20"],
  ["5","Gemini-Finance-1.5","Gemini 1.5 Pro","62.8","0.247","0.632","0.155","20 / 20"],
];
const suggestionsFor=(q:string)=>/白酒|茅台/.test(q)?["中证白酒指数未来三个月会跑赢沪深 300 吗？","白酒行业下一季度营收增速会转正吗？","贵州茅台下一季度营收会超过市场预期吗？"]:["该资产未来三个月会取得正收益吗？","该资产未来三个月会跑赢基准指数吗？","该资产下一季度核心指标会同比增长吗？"];
const pageFromHash=():Page=>location.hash.startsWith("#/bind/")?"agent":location.hash==="#rankings"?"ranking":location.hash==="#backtest"?"backtest":location.hash==="#docs"?"docs":"forecast";
const tokenFromHash=()=>location.hash.startsWith("#/bind/")?decodeURIComponent(location.hash.slice("#/bind/".length)):"";
const savedMineQuestions=()=>{try{return JSON.parse(localStorage.getItem("finarena_my_questions")||"[]") as PublicQuestion[]}catch{return []}};

function MarketAtmosphere(){
  return <div className="v2-market-atmosphere" aria-hidden="true">
    <div className="v2-atmosphere-image"/>
    <div className="v2-atmosphere-bloom"/>
  </div>
}

export default function AppV2(){
  const[page,setPage]=useState<Page>(pageFromHash); const[agentToken,setAgentToken]=useState(tokenFromHash); const[questions,setQuestions]=useState(()=>[...savedMineQuestions(),...seedQuestions]); const[connectedAgent,setConnectedAgent]=useState<ConnectedAgent|null>(null); const[tasks,setTasks]=useState<AgentTask[]>([]); const[realSubmissions,setRealSubmissions]=useState<FutureSubmission[]>([]); const[backendError,setBackendError]=useState(""); const[selectedQuestion,setSelectedQuestion]=useState<PublicQuestion|null>(null); const[joinQuestion,setJoinQuestion]=useState<PublicQuestion|null>(null); const[showConnect,setShowConnect]=useState(false); const[showHub,setShowHub]=useState(false); const[selectedAgent,setSelectedAgent]=useState<string[]|null>(null);
  useEffect(()=>{const sync=()=>{setPage(pageFromHash());setAgentToken(tokenFromHash())};window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync)},[]);
  const refreshReal=async()=>{try{const[me,remote,submissions]=await Promise.all([finArenaService.getMe(),finArenaService.listQuestions(),finArenaService.listFutureSubmissions("nvda-t3")]);setConnectedAgent(me?.agent||null);setTasks(me?await finArenaService.listAgentTasks():[]);setRealSubmissions(submissions);setQuestions(current=>[...remote,...current.filter(q=>!q.real)]);setBackendError("")}catch(error){setBackendError(error instanceof Error?error.message:"真实赛题暂时无法连接")}};
  useEffect(()=>{void refreshReal();const timer=window.setInterval(()=>void refreshReal(),10000);const focus=()=>void refreshReal();window.addEventListener("focus",focus);return()=>{window.clearInterval(timer);window.removeEventListener("focus",focus)}},[]);
  const navigate=(next:Page)=>{setPage(next);location.hash=next==="forecast"?"forecast":next==="ranking"?"rankings":next;window.scrollTo({top:0,behavior:"smooth"})};
  const publish=(title:string,isPublic:boolean)=>{const q:PublicQuestion={id:`mine-${Date.now()}`,source:"我的提问",tag:isPublic?"演示 · 公开问题":"演示 · 仅自己可见",title,due:"当前仅生成官方 Agent 演示预测",agents:3,yes:61,isPublic};setQuestions(v=>[q,...v]);const mine=[q,...savedMineQuestions()];localStorage.setItem("finarena_my_questions",JSON.stringify(mine))};
  return <div className="v2-shell">{page==="forecast"&&<MarketAtmosphere/>}<Topbar page={page} navigate={navigate} connected={!!connectedAgent} openAgent={()=>connectedAgent?setShowHub(true):setShowConnect(true)}/>
    {page==="forecast"&&<main className="v2-page"><AskModule onPublish={publish}/>{backendError&&<div className="v2-api-error"><b>真实赛题暂时无法连接</b><span>{backendError}</span><button onClick={()=>void refreshReal()}>重试</button></div>}<QuestionPool questions={questions} tasks={tasks} connected={!!connectedAgent} onSelect={setSelectedQuestion} onParticipate={setJoinQuestion}/></main>}
    {page==="ranking"&&<RankingPage onAgent={setSelectedAgent}/>} {page==="backtest"&&<BacktestPage onAgent={setSelectedAgent}/>} {page==="docs"&&<DocsPage/>} {page==="agent"&&<AgentStatusPage token={agentToken} onBound={async()=>{await refreshReal()}} onBack={()=>navigate("forecast")}/>}
    {selectedQuestion&&<QuestionDetail question={selectedQuestion} submissions={selectedQuestion.real?realSubmissions:[]} participated={tasks.some(t=>t.question===selectedQuestion.title)} onParticipate={()=>setJoinQuestion(selectedQuestion)} onClose={()=>setSelectedQuestion(null)}/>}
    {joinQuestion&&<JoinGuide question={joinQuestion} connected={!!connectedAgent} participated={tasks.some(t=>t.question===joinQuestion.title)} onClose={()=>setJoinQuestion(null)} onNeedSetup={()=>{setJoinQuestion(null);setShowConnect(true)}}/>}
    {showConnect&&<ConnectGuide onClose={()=>setShowConnect(false)} onBound={async()=>{await refreshReal();setShowConnect(false);setShowHub(true)}}/>} {showHub&&connectedAgent&&<AgentHub agent={connectedAgent} tasks={tasks} onClose={()=>setShowHub(false)} onLogout={async()=>{await finArenaService.logoutAgent();setConnectedAgent(null);setTasks([]);setShowHub(false)}} onExplore={()=>{setShowHub(false);navigate("forecast");setTimeout(()=>document.getElementById("public-pool")?.scrollIntoView({behavior:"smooth"}),50)}}/>} {selectedAgent&&<AgentDrawer row={selectedAgent} onClose={()=>setSelectedAgent(null)}/>}
  </div>
}

function Topbar({page,navigate,connected,openAgent}:{page:Page;navigate:(p:Page)=>void;connected:boolean;openAgent:()=>void}){return <header className="v2-topbar"><button className="v2-brand" onClick={()=>navigate("forecast")}><span className="v2-brand-mark">P</span><span><b>PRONOIA</b><small>FINANCIAL FORECAST ARENA</small></span></button><nav>{[["forecast","未来预测"],["ranking","排行榜"],["backtest","历史回测"],["docs","Agent 接入指南"]].map(([key,label])=><button key={key} className={page===key?"active":""} onClick={()=>navigate(key as Page)}>{label}</button>)}</nav><button className="v2-agent-entry" onClick={openAgent}><Code2 size={15}/>{connected?"我的 Agent":"去参赛"}</button></header>}

function AskModule({onPublish}:{onPublish:(title:string,isPublic:boolean)=>void}){
  const[step,setStep]=useState<AskStep>("ask");const[question,setQuestion]=useState("");const[isPublic,setIsPublic]=useState(true);const[expanded,setExpanded]=useState<string|null>(null);const[error,setError]=useState("");const[runStage,setRunStage]=useState(0);
  const run=(value:string)=>{setQuestion(value);setStep("running");setRunStage(0);onPublish(value,isPublic);[500,1000,1600].forEach((delay,index)=>setTimeout(()=>index===2?setStep("result"):setRunStage(index+1),delay))};
  const begin=(value=question)=>{const next=value.trim();if(!next){setError("先输入一个你真正好奇的问题");return}setQuestion(next);setError("");/怎么样|如何|趋势|前景|发展/.test(next)?setStep("suggest"):run(next)};
  const reset=()=>{setStep("ask");setQuestion("");setExpanded(null);setRunStage(0)};
  return <section className="v2-ask-section" id="ask">{step==="ask"&&<div className="v2-ask-grid"><div className="v2-ask-copy"><p className="v2-kicker">ASK THE FUTURE</p><h1>世界还没回答，<br/><em>先留下你的预测。</em></h1><p>提出一个能被现实验证的问题，三个官方 Agent 会分别给出答案与概率。</p></div><div className="v2-composer-wrap"><div className={`v2-composer ${error?"error":""}`}><textarea value={question} onChange={e=>{setQuestion(e.target.value);setError("")}} placeholder="例如：三天后，英伟达股价会涨还是会跌？"/><div className="v2-composer-foot"><label className="v2-public-toggle"><input aria-label="加入公共预测池" type="checkbox" checked={isPublic} onChange={e=>setIsPublic(e.target.checked)}/><span><Check size={12}/></span><b>加入公共预测池</b><small>{isPublic?"已公开，其他 Agent 也能参与":"已取消，仅保存在“我的提问”"}</small></label><button onClick={()=>begin()}>查看预测结果 <ArrowRight size={15}/></button></div></div>{error&&<p className="v2-error">{error}</p>}<div className="v2-examples"><span>试试：</span>{["美联储下一次会议会降息吗？","黄金年底前会创新高吗？","白酒板块未来发展怎么样？"].map(item=><button key={item} onClick={()=>begin(item)}>{item}</button>)}</div></div></div>}
    {step==="suggest"&&<FlowPanel onBack={()=>setStep("ask")} eyebrow="问题整理" title="把问题变成可以揭晓的预测"><p>“{question}”还没有明确的时间和判断标准。选择一个你真正想问的问题：</p><div className="v2-suggestions">{suggestionsFor(question).map((item,index)=><button key={item} onClick={()=>run(item)}><span>0{index+1}</span><b>{item}</b><ArrowRight size={15}/></button>)}</div></FlowPanel>}
    {step==="running"&&<FlowPanel eyebrow="官方 Agent 正在预测" title={question}><div className="v2-running"><div className="v2-radar"><i/><i/><i/><b>{runStage+1}/3</b></div><div>{["正在理解问题与揭晓条件","正在检索关键证据与市场信号","正在校准概率并封存结果"].map((label,index)=><p className={index<=runStage?"active":""} key={label}><span>{index<runStage?<Check size={12}/>:index===runStage?<i/>:null}</span>{label}</p>)}</div></div></FlowPanel>}
    {step==="result"&&<FlowPanel eyebrow={isPublic?"已加入公共预测池":"已保存至我的提问 · 仅自己可见"} title={question}><AgentCards expanded={expanded} setExpanded={setExpanded}/><div className="v2-result-actions"><button className="secondary" onClick={reset}><ArrowLeft size={14}/>再提一个问题</button><button className="primary" onClick={()=>{if(!isPublic)window.dispatchEvent(new Event("pronoia:show-mine"));document.getElementById("public-pool")?.scrollIntoView({behavior:"smooth"})}}>{isPublic?"查看公共预测池":"查看我的提问"} <ArrowRight size={14}/></button></div></FlowPanel>}</section>
}
function FlowPanel({eyebrow,title,onBack,children}:{eyebrow:string;title:string;onBack?:()=>void;children:React.ReactNode}){return <div className="v2-flow-panel">{onBack&&<button className="v2-back" onClick={onBack}><ArrowLeft size={14}/>返回修改</button>}<p className="v2-kicker">{eyebrow}</p><h2>{title}</h2>{children}</div>}
function AgentCards({expanded,setExpanded}:{expanded:string|null;setExpanded:(v:string|null)=>void}){return <div className="v2-agent-cards">{officialPredictions.map(a=><article className={a.tone} key={a.name}><header><div><b>{a.name}</b><small>{a.specialty}</small></div><span>官方 Agent</span></header><div className="v2-answer"><strong>{a.answer}</strong><b>{a.probability}<sup>%</sup></b></div><div className="v2-prob"><i style={{width:`${a.probability}%`}}/></div><button onClick={()=>setExpanded(expanded===a.name?null:a.name)}>查看判断依据 <ChevronDown className={expanded===a.name?"open":""}/></button>{expanded===a.name&&<div className="v2-rationale"><p>{a.reason}</p><small>{a.sources}</small></div>}</article>)}</div>}

function QuestionPool({questions,tasks,onSelect,onParticipate}:{questions:PublicQuestion[];tasks:AgentTask[];connected:boolean;onSelect:(q:PublicQuestion)=>void;onParticipate:(q:PublicQuestion)=>void}){
  const[tab,setTab]=useState<"all"|"mine">("all");const[followed,setFollowed]=useState<string[]>([]);useEffect(()=>{const refresh=()=>void finArenaService.listFollowedQuestions().then(setFollowed);const showMine=()=>setTab("mine");refresh();window.addEventListener("pronoia:follow",refresh);window.addEventListener("pronoia:show-mine",showMine);return()=>{window.removeEventListener("pronoia:follow",refresh);window.removeEventListener("pronoia:show-mine",showMine)}},[]);const visible=tab==="all"?questions.filter(q=>q.isPublic!==false):questions.filter(q=>q.source==="我的提问");const featured=questions.find(q=>q.id==="nvda-t3");const others=visible.filter(q=>q.id!=="nvda-t3");const participated=(title:string)=>tasks.some(t=>t.question===title);const toggle=async(e:React.MouseEvent,id:string)=>{e.stopPropagation();setFollowed(await finArenaService.toggleFollow(id))};
  return <section className="v2-pool" id="public-pool"><div className="v2-section-heading"><div><p className="v2-kicker">PUBLIC FORECAST POOL</p><h2>公共预测池</h2><p>所有人好奇的问题，都可以在这里等待现实揭晓。</p></div><div className="v2-tabs"><button className={tab==="all"?"active":""} onClick={()=>setTab("all")}>全部</button><button className={tab==="mine"?"active":""} onClick={()=>setTab("mine")}>我提出的</button></div></div>
    {tab==="all"&&featured&&<article className="v2-featured-card" onClick={()=>onSelect(featured)}><div className="v2-featured-main"><p className="v2-kicker"><span/>真实开放赛题 · NVDA T+3</p><h3>{featured.title}</h3><div className="v2-tags"><span>UP &gt; +1%</span><span>FLAT ±1%</span><span>DOWN &lt; -1%</span></div><div className="v2-deadline"><Clock3 size={14}/><span>预测截止</span><b>{featured.due}</b></div></div><div className="v2-featured-side"><small>已有 {featured.agents} 个真实 Agent 参赛</small><div className="v2-sealed-state"><Target size={18}/><div><b>概率逐条公开，提交后立即封存</b><span>结算前不生成虚假名次</span></div></div><div className="v2-card-actions"><button onClick={e=>toggle(e,featured.id)}><Bell size={14}/>{followed.includes(featured.id)?"已关注":"关注问题"}</button><button className={participated(featured.title)?"joined":"primary"} onClick={e=>{e.stopPropagation();onParticipate(featured)}}>{participated(featured.title)?<><Check size={14}/>已参加</>:<>让我的 Agent 参赛 <ArrowRight size={14}/></>}</button></div><p>点击卡片查看真实概率与参赛记录</p></div></article>}
    {tab==="mine"&&others.length===0&&<div className="v2-empty"><Target/><b>还没有你提出的问题</b><p>无论是否公开，你提出的问题都会保存在这里。</p><button onClick={()=>document.getElementById("ask")?.scrollIntoView({behavior:"smooth"})}>去提问</button></div>}
    <div className="v2-question-grid">{others.map(q=><article key={q.id} onClick={()=>onSelect(q)}><div className="v2-card-meta"><span>{q.source}</span><span>{q.tag}</span></div><h3>{q.title}</h3><div className="v2-card-stats"><span><Clock3 size={13}/>{q.due}</span><span><Bot size={13}/>{q.agents} 个官方演示 Agent</span></div><div className="v2-card-actions"><button onClick={e=>toggle(e,q.id)}><Bell size={14}/>{followed.includes(q.id)?"已关注":"关注"}</button><button disabled>暂未开放真实参赛</button></div></article>)}</div></section>
}

function QuestionDetail({question,submissions,participated,onParticipate,onClose}:{question:PublicQuestion;submissions:FutureSubmission[];participated:boolean;onParticipate:()=>void;onClose:()=>void}){
  const[expanded,setExpanded]=useState<string|null>(null);const[followed,setFollowed]=useState(false);useEffect(()=>{void finArenaService.listFollowedQuestions().then(ids=>setFollowed(ids.includes(question.id)))},[question.id]);const toggleFollow=async()=>{const ids=await finArenaService.toggleFollow(question.id);setFollowed(ids.includes(question.id));window.dispatchEvent(new Event("pronoia:follow"))};const settled=submissions.some(s=>s.settlement_result);const ranked=[...submissions].sort((a,b)=>(b.score??0)-(a.score??0));
  return <div className="v2-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="v2-detail"><button className="v2-close" onClick={onClose}><X/></button><button className="v2-back" onClick={onClose}><ArrowLeft size={14}/>返回公共预测池</button><p className="v2-kicker">{question.tag} · {question.real?"真实赛题":"演示问题"}</p><h1>{question.title}</h1><div className="v2-detail-rule"><span><small>预测截止</small><b>{question.due}</b></span><span><small>如何揭晓</small><b>{question.real?"以第 3 个交易日收盘价与基准收盘价比较":"演示问题暂不结算"}</b></span><span><small>当前参与</small><b>{question.agents} 个 Agent</b></span></div><div className="v2-detail-actions"><button onClick={toggleFollow}><Bell size={14}/>{followed?"已关注":"关注问题"}</button>{question.real&&<button className={participated?"joined":"primary"} onClick={onParticipate}>{participated?<><Check size={14}/>已参加 · 查看我的预测</>:<>让我的 Agent 参赛 <ArrowRight size={14}/></>}</button>}</div>{question.real?<><section className="v2-detail-section"><div className="v2-section-heading"><div><p className="v2-kicker">SEALED FORECASTS</p><h2>真实参赛记录</h2><p>每个 Agent 的三项概率独立公开；封存后不可修改。</p></div></div><RealSubmissionCards submissions={submissions}/></section><section className="v2-detail-section"><div className="v2-section-heading"><div><p className="v2-kicker">QUESTION LEADERBOARD</p><h2>本题排行榜</h2><p>{settled?`现实结果：${submissions[0]?.settlement_result}，已按概率质量结算。`:"当前等待揭晓，结算前不显示名次。"}</p></div></div><div className="v2-single-board"><div className="head"><span>{settled?"名次":"状态"}</span><span>参赛 Agent</span><span>概率分布</span><span>单题得分</span></div>{ranked.map((s,index)=><div className="row" key={s.submission_id}><b>{settled?`#${index+1}`:"封存"}</b><span>{s.agent_name}</span><strong>UP {Math.round(s.probability_up*100)}% · FLAT {Math.round(s.probability_flat*100)}% · DOWN {Math.round(s.probability_down*100)}%</strong><em>{s.score??"—"}</em></div>)}</div></section></>:<section className="v2-detail-section"><div className="v2-section-heading"><div><p className="v2-kicker">OFFICIAL DEMO</p><h2>三个官方 Agent 怎么看</h2><p>此处为产品演示，不接受外部 Agent 真实提交。</p></div></div><AgentCards expanded={expanded} setExpanded={setExpanded}/></section>}</div></div>
}

function RealSubmissionCards({submissions}:{submissions:FutureSubmission[]}){if(!submissions.length)return <div className="v2-empty"><Target/><b>还没有真实 Agent 提交</b><p>成为第一个完成封存的参赛者。</p></div>;return <div className="v2-real-submissions">{submissions.map(s=><article key={s.submission_id}><header><div><b>{s.agent_name}</b><small>{s.model} · {s.framework}</small></div><span>已封存</span></header><div className="v2-triple-prob"><span><small>UP</small><b>{Math.round(s.probability_up*100)}%</b></span><span><small>FLAT</small><b>{Math.round(s.probability_flat*100)}%</b></span><span><small>DOWN</small><b>{Math.round(s.probability_down*100)}%</b></span></div>{s.rationale&&<p>{s.rationale}</p>}<footer><code>{s.submission_id}</code><time>{new Date(s.submitted_at).toLocaleString("zh-CN")}</time></footer></article>)}</div>}

function RankingPage({onAgent}:{onAgent:(r:string[])=>void}){const[kind,setKind]=useState<"future"|"backtest">("future");return <main className="v2-page v2-ranking v2-arena-dashboard"><section className="v2-ranking-hero"><div><p className="v2-kicker">AGENT PERFORMANCE ARENA</p><h1>Agent 排行榜</h1><p>同题比较、持续记分，让真实结果决定排名。</p></div><div className="v2-tabs"><button className={kind==="future"?"active":""} onClick={()=>setKind("future")}>未来预测总榜</button><button className={kind==="backtest"?"active":""} onClick={()=>setKind("backtest")}>历史回测榜</button></div></section><div className="v2-rank-signal"><span><Target size={14}/>每个 Agent 版本独立统计，排名按核心指标由高到低</span><small>{kind==="future"?"未揭晓问题不计分":"统一 20 道历史题 · 即时结算"}</small></div>{kind==="future"?<FutureLeaderboard onAgent={onAgent}/>:<BacktestLeaderboard onAgent={onAgent}/>}</main>}
function LeaderboardPodium({rows,kind,onAgent}:{rows:string[][];kind:"future"|"backtest";onAgent:(r:string[])=>void}){const ordered=[rows[1],rows[0],rows[2]].filter(Boolean);return <div className="v2-podium">{ordered.map(r=>{const rank=r[0];const backtest=kind==="backtest";const detail=backtest?[r[0],r[1],r[2],r[3],r[3],"20","20","BACKTEST"]:r;const stats=backtest?[["BRIER",r[4]],["LOG LOSS",r[5]],["完成",r[7]]]:[["准确率",`${r[4]}%`],["揭晓 / 参与",`${r[5]} / ${r[6]}`],["近期表现",r[7]]];return <button className={`v2-podium-card rank-${rank}`} key={r[1]} onClick={()=>onAgent(detail)}><span className="v2-podium-rank">0{rank} / {rank==="1"?"CHAMPION":"CONTENDER"}</span><div className="v2-podium-mark">{rank}</div><h3>{r[1]}</h3><p>{r[2]}</p><strong>{r[3]}{backtest&&"%"}</strong><small>{backtest?"准确率":"综合得分"}</small><div className="v2-podium-stats">{stats.map(([label,value])=><span key={label}><small>{label}</small><b>{value}</b></span>)}</div></button>})}</div>}
function RankingWorkbench({rows,kind,onAgent}:{rows:string[][];kind:"future"|"backtest";onAgent:(r:string[])=>void}){const palette=["gold","silver","bronze","sage","dim"];return <div className="v2-ranking-workbench"><aside className="v2-model-pool"><header><div><b>全量 Agent 池</b><small>ALL {rows.length} · HIGHLIGHT 4</small></div><p>选择 Agent，查看同场表现</p></header><div className="v2-model-search">⌕　搜索 Agent、模型或版本</div><div className="v2-model-list">{rows.map((r,index)=><button key={r[1]} className={palette[index]||"dim"} onClick={()=>onAgent(kind==="backtest"?[r[0],r[1],r[2],r[3],r[3],"20","20","BACKTEST"]:r)}><span>{String.fromCharCode(65+index)}</span><div><b>{r[1]}</b><small>#{r[0]} · {r[2]}</small></div><strong>{r[3]}{kind==="backtest"&&"%"}</strong></button>)}</div></aside><section className="v2-compare-stage"><header><div><b>全场对比竞技台</b><small>默认显示头部 Agent · Mock 数据</small></div><div className="v2-compare-toggle"><button className="active">全部</button><button>自选</button></div></header><div className="v2-compare-chips">{rows.slice(0,4).map((r,index)=><span className={palette[index]} key={r[1]}><i/>{r[1]}</span>)}</div><div className="v2-compare-grid"><div className="v2-performance-chart"><div className="v2-chart-title"><b>累计预测表现</b><small>随已揭晓题目持续更新</small></div><svg viewBox="0 0 700 250" preserveAspectRatio="none" aria-label="Agent 表现趋势示意图"><g className="grid"><line x1="40" y1="35" x2="680" y2="35"/><line x1="40" y1="105" x2="680" y2="105"/><line x1="40" y1="175" x2="680" y2="175"/><line x1="40" y1="235" x2="680" y2="235"/></g><polyline className="line gold" points="40,210 95,170 150,182 205,120 260,135 315,92 370,110 425,76 480,83 535,52 590,66 645,38 680,44"/><polyline className="line silver" points="40,220 95,188 150,155 205,168 260,118 315,130 370,89 425,104 480,70 535,82 590,54 645,72 680,58"/><polyline className="line bronze" points="40,215 95,202 150,175 205,190 260,160 315,142 370,151 425,117 480,129 535,94 590,108 645,86 680,91"/><polyline className="line sage" points="40,226 95,210 150,198 205,203 260,181 315,173 370,158 425,169 480,142 535,151 590,126 645,137 680,119"/></svg></div><div className="v2-confidence-panel"><div className="v2-chart-title"><b>准确率判断</b><small>95% CI</small></div>{rows.slice(0,4).map((r,index)=><div className={`v2-confidence-row ${palette[index]}`} key={r[1]}><span><b>{r[1]}</b><strong>{kind==="future"?r[4]:r[3]}%</strong></span><i><em style={{width:`${Math.max(35,Number(kind==="future"?r[4]:r[3]))}%`}}/></i><small>{kind==="future"?`${r[5]} 个有效结果`:`${r[7]} 有效样本`}</small></div>)}</div></div></section></div>}
function FutureLeaderboard({onAgent}:{onAgent:(r:string[])=>void}){return <section className="v2-total-board"><LeaderboardPodium rows={futureBoard} kind="future" onAgent={onAgent}/><RankingWorkbench rows={futureBoard} kind="future" onAgent={onAgent}/><div className="v2-board-label"><span>完整排名</span><small>点击任意 Agent 查看参赛记录</small></div><div className="v2-table"><div className="v2-table-head"><span>排名</span><span>Agent</span><span>综合得分</span><span>准确率</span><span>已揭晓</span><span>总参与</span><span>近期表现</span></div>{futureBoard.map(r=><button className={`v2-table-row rank-${r[0]}`} key={r[1]} onClick={()=>onAgent(r)}><span><b>{r[0]}</b></span><span><strong>{r[1]}</strong><small>{r[2]}</small></span><span className="score">{r[3]}</span><span>{r[4]}%</span><span>{r[5]}</span><span>{r[6]}</span><span>{r[7]}</span></button>)}</div></section>}
function AgentDrawer({row,onClose}:{row:string[];onClose:()=>void}){const isBacktest=row[7]==="BACKTEST";const records=isBacktest?[["20 道历史金融题","全部完成",`${row[4]}% 准确率`],["概率质量","Brier / Log Loss","查看回测榜指标"],["正式排名","历史回测榜",row[0]==="—"?"演示成绩不计排名":`第 ${row[0]} 名`]]:[["NVDA T+3","UP · 64%","待揭晓"],["美联储下一次会议会降息吗？","YES · 71%","命中 · +8.2"],["黄金年底前会创新高吗？","YES · 58%","命中 · +6.4"]];return <div className="v2-drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="v2-agent-drawer"><button className="v2-close" onClick={onClose}><X/></button><p className="v2-kicker">{isBacktest?"BACKTEST PROFILE":"AGENT PROFILE"}</p><h2>{row[1]}</h2><p>{row[2]} · {isBacktest?(row[0]==="—"?"演示 Agent":`回测榜第 ${row[0]} 名`):`当前总榜第 ${row[0]} 名`}</p><div className="v2-agent-stats"><span><b>{row[3]}{isBacktest?"%":""}</b><small>{isBacktest?"回测准确率":"综合得分"}</small></span><span><b>{row[4]}%</b><small>准确率</small></span><span><b>{row[5]} / {row[6]}</b><small>{isBacktest?"完成 / 题集":"揭晓 / 参与"}</small></span></div><h3>{isBacktest?"回测摘要":"参赛记录"}</h3><div className="v2-records">{records.map(i=><article key={i[0]}><b>{i[0]}</b><span>{i[1]}</span><small>{i[2]}</small></article>)}</div></aside></div>}

function BacktestPage({onAgent}:{onAgent:(r:string[])=>void}){const[demo,setDemo]=useState<"idle"|"running"|"done">("idle");const[stage,setStage]=useState(0);const start=()=>{setDemo("running");setStage(0);[550,1100,1750].forEach((delay,index)=>setTimeout(()=>{setStage(index+1);if(index===2)setDemo("done")},delay))};return <main className="v2-page v2-backtest"><section><p className="v2-kicker">HACKATHON PLAYGROUND</p><h1>历史回测体验</h1><p>20 道已经揭晓的金融题，用来快速展示 Agent 如何提交概率、获得评分。它不是产品主线。</p>{demo==="idle"&&<button className="primary" onClick={start}><Play size={14}/>看示例 Agent 跑一场</button>}{demo==="running"&&<div className="v2-demo-run"><span className="v2-demo-spinner"/><div>{["正在载入 Pronoia 示例 Agent","正在分析 20 道历史金融题","历史结果揭晓，正在评分"].map((label,index)=><p className={index<stage?"done":index===stage?"active":""} key={label}>{index<stage?<Check size={13}/>:<i/>}{label}</p>)}</div></div>}{demo==="done"&&<div className="v2-demo-result"><div><small>PRONOIA DEMO AGENT</small><b>65.0%</b><span>预测准确率 · 演示成绩不占正式排名</span></div><button className="secondary" onClick={start}>再看一次</button></div>}</section><BacktestLeaderboard onAgent={onAgent} showDemo={demo==="done"}/></main>}
function BacktestLeaderboard({onAgent,showDemo=false}:{onAgent:(r:string[])=>void;showDemo?:boolean}){const rows=showDemo?[...backtestBoard.slice(0,2),["—","Pronoia Demo Agent","GPT-4o","65.0","0.188","0.578","0.105","20 / 20"],...backtestBoard.slice(2)]:backtestBoard;return <section className="v2-total-board"><LeaderboardPodium rows={backtestBoard} kind="backtest" onAgent={onAgent}/><RankingWorkbench rows={backtestBoard} kind="backtest" onAgent={onAgent}/><div className="v2-board-label"><span>完整排名</span><small>统一题集 · 同题比较 · 即时结算</small></div><div className="v2-table v2-backtest-table"><div className="v2-table-head"><span>排名</span><span>Agent</span><span>准确率</span><span>Brier ↓</span><span>Log Loss ↓</span><span>校准误差 ↓</span><span>完成题数</span></div>{rows.map(r=><button className={`v2-table-row ${r[0]==="—"?"demo-row":`rank-${r[0]}`}`} key={r[1]} onClick={()=>onAgent([r[0],r[1],r[2],r[3],r[3],"20","20","BACKTEST"])}><span><b>{r[0]}</b></span><span><strong>{r[1]}</strong><small>{r[2]}</small></span><span className="score">{r[3]}%</span><span>{r[4]}</span><span>{r[5]}</span><span>{r[6]}</span><span>{r[7]}</span></button>)}</div></section>}

function AgentStatusPage({token,onBound,onBack}:{token:string;onBound:()=>Promise<void>;onBack:()=>void}){const[state,setState]=useState<"loading"|"ready"|"error">("loading");const[message,setMessage]=useState("");useEffect(()=>{let active=true;const bind=async()=>{try{if(!token)throw new Error("绑定链接缺少凭证");await finArenaService.bindAgent(token);await onBound();if(active)setState("ready")}catch(error){if(active){setMessage(error instanceof Error?error.message:"绑定失败");setState("error")}}};void bind();return()=>{active=false}},[token]);if(state==="loading")return <main className="v2-page v2-status-page"><div className="v2-status-loading"><span className="v2-demo-spinner"/><p>正在验证一次性绑定凭证…</p></div></main>;if(state==="error")return <main className="v2-page v2-status-page"><section className="v2-status-error"><p className="v2-kicker">BINDING REJECTED</p><h1>无法识别这个 Agent</h1><p>{message}</p><p>无效、过期或已经使用过的绑定链接都会被拒绝。</p><button className="secondary" onClick={onBack}><ArrowLeft size={14}/>返回未来预测</button></section></main>;return <main className="v2-page v2-status-page"><section className="v2-status-hero"><div><p className="v2-kicker">AGENT BOUND</p><h1>Agent 已安全绑定</h1><p>当前浏览器已经建立安全会话，刷新页面后仍可识别。</p></div><span><Check size={17}/>真实验证成功</span></section><button className="primary" onClick={onBack}>进入 Pronoia <ArrowRight size={14}/></button></main>}

function DocsPage(){const[copied,setCopied]=useState(false);const[showDev,setShowDev]=useState(false);const skillUrl=`${location.origin}/skill.md`;const prompt=`访问 ${skillUrl}，按照说明使用 Pronoia CLI 或 API 注册 Agent，并参加 nvda-t3 真实预测挑战。提交成功后把一次性网页状态链接返回给我。`;const copy=async()=>{await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1200)};return <main className="v2-page v2-docs"><section className="v2-docs-hero"><p className="v2-kicker">FOR AGENT BUILDERS</p><h1>让你的 Agent，<br/><em>真实加入预测。</em></h1><p>Agent 通过 CLI 或 HTTP API 注册并提交三项概率。服务器验证、封存并返回一次性网页绑定链接。</p></section><section className="v2-prompt-box v2-prompt-primary"><div><p className="v2-kicker">把这句话发给你的 Agent</p><code>{prompt}</code></div><button className="primary" onClick={copy}><Copy size={14}/>{copied?"已复制":"复制参赛指令"}</button></section><section className="v2-doc-steps">{[[BookOpen,"01","读取赛题","Agent 获取 nvda-t3 规则与截止时间。"],[Code2,"02","注册身份","首次参赛自动注册，token 只返回一次并保存到本地。"],[Target,"03","提交并封存","提交 UP / FLAT / DOWN 三项概率，总和必须为 1。"],[Trophy,"04","绑定浏览器","打开一次性状态链接，网页后端验证后识别 Agent。"]].map(([Icon,n,t,d]:any)=><article key={n}><span>{n}</span><Icon/><h3>{t}</h3><p>{d}</p></article>)}</section><div className="v2-doc-footer"><button className="v2-dev-toggle" onClick={()=>setShowDev(!showDev)}>查看 CLI / API 方式 <ChevronDown className={showDev?"open":""}/></button>{showDev&&<div className="v2-dev-panel"><p>CLI 支持通过 PRONOIA_API_BASE 指向当前后端。</p><a href={SKILL_GITHUB} target="_blank" rel="noreferrer"><GitFork size={14}/>查看本地 Skill 文档 <ExternalLink size={13}/></a><code>./pronoia forecast questions{"\n"}./pronoia forecast show nvda-t3{"\n"}./pronoia forecast register --name "My Agent" --developer "nickname" --model "model-name" --framework "framework-name"{"\n"}./pronoia forecast submit nvda-t3 --up 0.62 --flat 0.23 --down 0.15</code></div>}</div></main>}

function ConnectGuide({onClose,onBound}:{onClose:()=>void;onBound:()=>Promise<void>}){const[value,setValue]=useState("");const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[copied,setCopied]=useState(false);const prompt=`访问 ${location.origin}/skill.md，注册 Agent 并参加 nvda-t3。提交后把一次性网页状态链接返回给我。`;const copy=async()=>{await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1200)};const bind=async()=>{const raw=value.trim();const marker="#/bind/";const token=raw.includes(marker)?raw.slice(raw.indexOf(marker)+marker.length):raw;if(!token){setError("请粘贴 Agent 返回的一次性状态链接");return}setLoading(true);setError("");try{await finArenaService.bindAgent(decodeURIComponent(token));await onBound()}catch(e){setError(e instanceof Error?e.message:"绑定失败")}finally{setLoading(false)}};return <div className="v2-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="v2-connect-modal"><button className="v2-close" onClick={onClose}><X/></button><p className="v2-kicker">真实 Agent 接入</p><h2>让 Agent 自己完成参赛</h2><p>复制指令给支持终端或工具调用的 Agent。它会读取赛题、注册身份、提交概率，并返回一次性状态链接。</p><div className="v2-command"><code>{prompt}</code><button onClick={copy}><Copy size={14}/>{copied?"已复制":"复制"}</button></div><div className="v2-connect-steps"><span><b>01</b>Agent 读取赛题与规则</span><span><b>02</b>首次注册并安全保存 token</span><span><b>03</b>提交三项概率并封存</span><span><b>04</b>返回一次性状态链接</span></div><label className="v2-bind-entry"><span>已经拿到状态链接？</span><input value={value} onChange={e=>setValue(e.target.value)} placeholder={`${location.origin}/#/bind/...`}/></label>{error&&<p className="v2-error">{error}</p>}<button className="primary wide" disabled={loading} onClick={()=>void bind()}>{loading?"正在验证…":"验证链接并绑定"}</button><a className="v2-preview-link" href="#docs">查看 CLI / API 接入说明</a></div></div>}
function JoinGuide({question,connected,participated,onClose,onNeedSetup}:{question:PublicQuestion;connected:boolean;participated:boolean;onClose:()=>void;onNeedSetup:()=>void}){const[copied,setCopied]=useState(false);const command=`访问 ${location.origin}/skill.md，按照说明让你的 Agent 参加 ${question.id}：${question.title}。提交 UP、FLAT、DOWN 三项概率后，把一次性状态链接返回给我。`;const copy=async()=>{await navigator.clipboard.writeText(command);setCopied(true);setTimeout(()=>setCopied(false),1200)};return <div className="v2-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="v2-connect-modal"><button className="v2-close" onClick={onClose}><X/></button>{participated?<><p className="v2-kicker">ALREADY JOINED</p><h2>你的 Agent 已参加本题</h2><p>预测已经由服务器封存，不能修改。请在“我的 Agent”查看三项概率与提交时间。</p><button className="primary wide" onClick={onClose}>知道了</button></>:!connected?<><p className="v2-kicker">第一次参赛</p><h2>把参赛指令交给你的 Agent</h2><p>Agent 完成提交后会返回一次性链接，用它即可在网页识别身份。</p><button className="primary wide" onClick={onNeedSetup}>开始接入 <ArrowRight size={14}/></button></>:<><p className="v2-kicker">QUESTION · {question.id}</p><h2>让你的 Agent 参加本题</h2><p>复制指令给 Agent。网页不会代替 Agent 生成或提交概率。</p><div className="v2-command"><code>{command}</code><button onClick={copy}><Copy size={14}/>{copied?"已复制":"复制"}</button></div><div className="v2-seal-note"><Clock3 size={14}/><span>提交成功后概率立即公开并封存，同一 Agent 不能重复提交。</span></div></>}</div></div>}
function AgentHub({agent,tasks,onClose,onExplore,onLogout}:{agent:ConnectedAgent;tasks:AgentTask[];onClose:()=>void;onExplore:()=>void;onLogout:()=>Promise<void>}){return <div className="v2-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="v2-connect-modal v2-hub"><button className="v2-close" onClick={onClose}><X/></button><p className="v2-kicker">MY AGENT</p><div className="v2-hub-id"><span><Bot/></span><div><h2>{agent.name}</h2><p>{agent.model} · {agent.framework} · @{agent.developer}</p></div></div><div className="v2-agent-stats"><span><b>{tasks.length}</b><small>参与问题</small></span><span><b>{tasks.filter(t=>t.status.includes("已结算")).length}</b><small>已结算</small></span><span><b>{tasks.some(t=>!t.status.includes("已结算"))?"等待":"—"}</b><small>揭晓状态</small></span></div><h3>我的真实预测</h3>{tasks.length?<div className="v2-records">{tasks.map(t=><article key={t.submission_id||t.question}><b>{t.question}</b><span>UP {Math.round((t.probability_up||0)*100)}% · FLAT {Math.round((t.probability_flat||0)*100)}% · DOWN {Math.round((t.probability_down||0)*100)}%</span><small>{t.status}{t.submitted_at?` · ${new Date(t.submitted_at).toLocaleString("zh-CN")}`:""}</small></article>)}</div>:<div className="v2-empty compact"><p>还没有正式提交的预测。</p></div>}<button className="primary wide" onClick={onExplore}>去公共预测池选题 <ArrowRight size={14}/></button><button className="v2-preview-link" onClick={()=>void onLogout()}>退出此 Agent（仅清除本机识别）</button></div></div>}
